import Navbar from "@/components/ui/navbar";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Open_Sans, Overpass_Mono } from "next/font/google";
import "./globals.css";

const fontMono = Overpass_Mono({
	variable: "--font-mono",
	subsets: ["latin"],
	weight: ["400"],
});

const fontSans = Open_Sans({
	variable: "--font-sans",
	subsets: ["latin"],
	weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// Inline script to prevent hydration mismatch
	const setThemeScript = `
	  (function() {
		const theme = localStorage.getItem('theme');
		if (theme) {
		  document.documentElement.className = theme;
		  document.documentElement.style.colorScheme = theme;
		} else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
		  document.documentElement.className = 'dark';
		  document.documentElement.style.colorScheme = 'dark';
		} else {
		  document.documentElement.className = 'light';
		  document.documentElement.style.colorScheme = 'light';
		}
	  })();
	`;

	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				{/* Inject the theme initializer script */}
				<script dangerouslySetInnerHTML={{ __html: setThemeScript }} />
			</head>
			<body className={cn(fontMono.variable, fontSans.variable, "font-sans", "antialiased", "scroll-smooth")}>
				<ThemeProvider attribute="class" defaultTheme="light" enableSystem>
					<Navbar />
					<div className="container py-0 mx-auto flex items-center justify-center px-4">{children}</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
